language: node_js
node_js:
 - "8.11.1"
cache:
  directories:
    - "node_modules"
before_install:
  echo "@fortawesome:registry=https://npm.fontawesome.com/\${FONTAWESOME_TOKEN}" > .npmrc
  npm install -g webpack-cli
#  sudo ldconfig
#  sudo apt-get install nasm
install:
  - npm install
script:
  - npm run build
deploy:
  on:
    branch: develop
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
after_deploy:
