language: node_js
node_js:
 - "node"
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  # Build your site (e.g., HTML, CSS, JS) here.
  - npm run build
deploy:
  on:
    branch: develop
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
after_deploy:
